### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kogeshu** [Chase1803/Gloomy.cc#9]
Which version of Windows does it work on? What is the rendering mode?

**Comment by kogeshu** [comment]
When I get Run Fortnite and start it, the menu doesn't appear no matter what key I press.

**Comment by Chase1803** [comment]
Press f2

**Comment by kogeshu** [comment]
I'll try

**Comment by kogeshu** [comment]
![image](https://user-images.githubusercontent.com/105981418/169665252-0ef3437f-26c6-4bce-8c9d-b6185c620966.png)
Nothing reacts.

**Comment by Chase1803** [comment]
Don’t run in debug mode? Compile as release and run as admin

**Comment by kogeshu** [comment]
Running with administrator privileges in release mode.

**Comment by Chase1803** [comment]
Debug if driver is loaded, CMD, sc query SandyBridge

**Comment by kogeshu** [comment]
What is a driver?

**Comment by kogeshu** [comment]
C:\Users\user>sc query SandyBridge
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.

**Comment by kogeshu** [comment]
What should i do?

**Comment by Chase1803** [comment]
Try downloading the latest one and compile it

**Comment by kogeshu** [comment]
It doesn't work. It remains black.

**Comment by kogeshu** [comment]
Is Fortnite rendering mode etc. relevant?

**Comment by Chase1803** [comment]
Uh no idea try debugging why driver isn't loading in the first place
